### ISSUE TITLE
Write openflights service

### ISSUE THREAD

**Issue by sr** [sr/operator#4]
I want a simple operator frontend for <https://github.com/peter-edge/openflights-go>. It should be able to tell me about airport, routes, and calculate miles.

- [ ] MAYBE Fix protoc-gen-operatorcmd to work with openflights.proto. It currently segfaults. I believe this due to the use of EmptyMessage in the openflights service. This may not be necessary as we might have to use a custom client anyway (use openflight local mode)

**Comment by lstoll** [comment]
RIP
